### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by zzjss12** [vul337/jTrans#1]
你好，我查看了pkl文件 但没明白你的组织形式，事实上，我需要有监督的（基本块的）数据集。
你能稍微解释下你的数据集组织格式吗。
非常感谢！
下面是部分pkl文件里的内容：

61808
['lea     rdi, byte_1A8C8', 'lea     rax, byte_1A8C8', 'cmp     rax, rdi', 'jz      short locret_F198', 'mov     rax, cs:_ITM_deregisterTMCloneTable_ptr', 'test    rax, rax', 'jz      short locret_F198', 'jmp     rax', 'retn']
b'H\x8d=Q\xb7\x00\x00H\x8d\x05J\xb7\x00\x00H9\xf8t\x15H\x8b\x05V\xae\x00\x00H\x85\xc0t\t\xff\xe0\xc3'
DiGraph with 4 nodes and 4 edges
{"directed": true, "graph": {"c_state": [71, 80], "c_expr": [52, 64], "c_int": [], "c_str": [], "m_int": [], "arg_num": 0, "hash": "67e65a2c3055eb755264e0726e9a82fd"}, "nodes": [{"id": 1, "feat": [[4, 83, 73, 74]]}], "links": [{"source": 1, "target": 1}], "multigraph": false}
61856
['lea     rdi, byte_1A8C8', 'lea     rsi, byte_1A8C8', 'sub     rsi, rdi', 'mov     rax, rsi', 'shr     rsi, 3Fh', 'sar     rax, 3', 'add     rsi, rax', 'sar     rsi, 1', 'jz      short locret_F1D8', 'mov     rax, cs:_ITM_registerTMCloneTable_ptr', 'test    rax, rax', 'jz      short locret_F1D8', 'jmp     rax', 'retn']
b'H\x8d=!\xb7\x00\x00H\x8d5\x1a\xb7\x00\x00H)\xfeH\x89\xf0H\xc1\xee?H\xc1\xf8\x03H\x01\xc6H\xd1\xfet\x14H\x8b\x05%\xae\x00\x00H\x85\xc0t\x08\xff\xe0\xc3'
DiGraph with 4 nodes and 4 edges
{"directed": true, "graph": {"c_state": [71, 80], "c_expr": [61], "c_int": [0], "c_str": [], "m_int": [0], "arg_num": 0, "hash": "321dd7553e44240da0cbae6772c53494"}, "nodes": [{"id": 1, "feat": [[4, 75, 73, 74]]}], "links": [{"source": 1, "target": 1}], "multigraph": false}

**Comment by Hustcw** [comment]
Overall each directory contains the features of binary compiled from the same source code at different optimization levels. Except for `saved_index.pkl`, the file name identifies the binary function features of different optimization levels, where each pickle file is a dictionary, the key is the function name, and the value is the function feature, in the following form
```python
 {
       'foo': [
            0x400000, # function_addr
            ['sub rbp, rsp', 'ret'], # asm_list
            b"\x48\x29\xe5\xc3", # raw bytes
            cfg, # networkx DiGraph
            binaryai_feature
        ],
       'bar': [
           ...
       ]
}
```
As shown above, the features are **function address**, **assembly string array**, **raw bytes**, **cfg in networkx** and **binaryai_ feature** (which is used for binaryai SDK). 

If you want supervised training data, you can prepare your own data by picking features from these files which have the same function name. Also, you can use the `saved_index.pkl` file, which is organized in the following form:
```python
{
       'foo': [
            unpair_foo_O0, # unpair_func_foo_O0
            unpair_foo_O1, # unpair_func_foo_O1
            unpair_foo_O2, # unpair_func_foo_O2
            ...
        ],
        'bar': [
            ...
        ]
}
```

For more details, you can check [playdata.py](https://github.com/vul337/jTrans/blob/main/datautils/playdata.py) in datautils.

**Comment by zzjss12** [comment]
你好！
save_index.pkl文件和其它五个不同编译文件之间的关系是什么？
另外我发现不同编译等级的文件里有相同的函数名，这意味着它们就能形成一对函数级别的克隆对（groundtruth为1)吗？
事实上我想要更细粒度的数据集---基本块（basic block) 但好像里面是函数粒度的。
有其它方法得到基本块粒度的数据集吗？

**Comment by Hustcw** [comment]
Sorry, we do not provide basic block level datasets. As I mentioned above, `saved_index.pkl` is used for parsing functions, which contains the functions appear in the other files.

**Comment by zzjss12** [comment]
![image](https://user-images.githubusercontent.com/66284098/174761455-79e58c76-49ec-4eef-b04d-dbb66fbcf52b.png)

cvlist
experiments
models

请问这上面三个文件是什么？
有关数据集的已经更新完了吗？

**Comment by Hustcw** [comment]
- `csvlist`: the package name list of each dataset
- `experiments`: experiment results 
- `models`: pre-trained and fine-tuned model
You can check the README.md and our code for more details. We have released all the extracted features in our datasets. In the future, we are going to enlarge our BinaryCorp and release  raw binaries.
