### ISSUE TITLE
problem with access to dataset

### ISSUE THREAD

**Issue by ggitcoder** [vul337/jTrans#10]
Hi, I'm trying to replicate your work, but the website for dataset sharing seems to be temporarily down. I would appreciate it if you could  fix it up.

**Comment by Hustcw** [comment]
Thank you for your interest in the dataset and for bringing to my attention that the website for dataset sharing was down temporarily. I apologize for the inconvenience this caused you. To download the dataset, I would suggest using the NextCloud client which would be more stable.
