### ISSUE TITLE
 BinBertModel 

### ISSUE THREAD

**Issue by xiaolang01** [vul337/jTrans#11]
Could you please tell me the function of the code
’‘’
 self.embeddings.position_embeddings=self.embeddings.word_embeddings
‘’‘
 in BinBertModel in finetune.py?

**Comment by Hustcw** [comment]
This is one method to implement jTrans, you can check the dictionary we use, which starts from JUMP_ADDR_XXX. We shared the parameters of position embedding and token embedding during training and inference. For specific details, please take a look at our paper.
