### ISSUE TITLE
About the Binarycorp Dataset's optimization level

### ISSUE THREAD

**Issue by pyz-creeper** [vul337/jTrans#17]
Thank you for your really good dataset and amazing papaer. How many optimization levels are included in the dataset? I am conducting some preprocess methods on the dataset. It would be really useful if you could provide me with some detailed information.

**Comment by Hustcw** [comment]
There are a total of five optimization levels included in the dataset: O0, O1, O2, O3, and Os.

**Comment by pyz-creeper** [comment]
Thanks. It helps a lot
