### ISSUE TITLE
binaryai.ida isuue 

### ISSUE THREAD

**Issue by roytalman** [vul337/jTrans#23]
I am trying to process my own data and I get an error for line 79 in process.py -
binaryai.ida.get_func_feature(func)

It says that binaryai does not have ida module.
I tried to load older versions of binaryai but it didnt solve it.

**Comment by Hustcw** [comment]
The binaryai feature is only used for evaluating binaryai model. If you only want to use jTrans, you can ignore those part

**Comment by roytalman** [comment]
Thanks for the quick replay. So if I want to extract the jTrans embedding features, I can replace this line:
return  binaryai.ida.get_func_feature(func)
with :
return [ ]
?

**Comment by Hustcw** [comment]
yep

**Comment by roytalman** [comment]
Thanks a lot
