### ISSUE TITLE
issue about data.py

### ISSUE THREAD

**Issue by chaofly** [vul337/jTrans#24]
In [data.py](https://github.com/vul337/jTrans/blob/main/data.py) line 176.  I think the code should be `if self.opt != None`. In your code, the same function with different opt is saved in one list. When finetuning for BCSD, it should randomly pick a pair of similar functions with different opt.   

![1701421511601](https://github.com/vul337/jTrans/assets/24863516/3ee7c342-cab7-4086-9e10-831999a4215e)

**Comment by Hustcw** [comment]
I apologize for the mistake. It seems that the issue may be due to a mismatch between the versions of data.py and finetune.py. If you use opt=None during training, it should work as expected.

**Comment by Hustcw** [comment]
Bug fixed, many thanks
