### ISSUE TITLE
训练和测试结果差距太大

### ISSUE THREAD

**Issue by zzjss12** [vul337/jTrans#26]
你好，有一个问题：
下图为训练过程的结果：
![VX8IRK`3%J~W8CPE(M~ SME](https://github.com/vul337/jTrans/assets/66284098/1d4ac115-9a2c-43c3-8b88-17f0865147d6)

下图为测试结果
![~C@V%P2 }YYBU8X9_C4C AJ](https://github.com/vul337/jTrans/assets/66284098/d0b789f1-fe87-4fb9-b24e-6b9175a3b0f4)
能解释一下 结果差距这么大的原因吗

**Comment by Hustcw** [comment]
可能的原因是你训练用来validate的poolsize和测试使用的不一样

**Comment by zzjss12** [comment]
好的谢谢 已经解决了
