### ISSUE TITLE
Questions about cross-architecture and cross-compiler datasets

### ISSUE THREAD

**Issue by lzy248** [vul337/jTrans#27]
I recently read this paper and found it very interesting.I was wondering if you have considered using cross-architecture compiler datasets to test the methods proposed in your paper?
In addition, I have no idea how to use "tokenizer.py" to generate a new "vocab.txt" for other or cross architecture dataset.

**Comment by Hustcw** [comment]
That's an interesting question. We need different tokenization methods for different architectures if we use assembly code directly. Try to use IR (e.g., micro-code, pcode or BinaryNinja IR) might be a good idea for cross architecture scenarios :)

**Comment by lzy248** [comment]
thanks for  helpful reply:)

**Comment by Hustcw** [comment]
We release a new model based on BinaryNinja MLIL at https://github.com/Hustcw/CEBin :)
