### ISSUE TITLE
PoolSize,supervised 

### ISSUE THREAD

**Issue by zzjss12** [vul337/jTrans#5]
What does poolsize mean in the paper? How can a supervised method be compared with the experiment?
Thank you for your answer.

**Comment by Hustcw** [comment]
Poolsize means the size of the function pool of the BSCD task (Section 5.3).  If the supervised method is able to determine whether two functions are similar, it might output a similarity score. You can give a rank according to the similarity score and calculate the evaluation metrics. The [fasteval.py](https://github.com/vul337/jTrans/blob/main/fasteval.py) shows the evaluation process we did in our experiment.

**Comment by zzjss12** [comment]
thanks!
![image](https://user-images.githubusercontent.com/66284098/178883781-6b125039-71b4-4373-a1fd-4746ab34c38d.png)
![image](https://user-images.githubusercontent.com/66284098/178883803-a14e3d14-827d-4eac-b8eb-95d461968ad8.png)
![image](https://user-images.githubusercontent.com/66284098/178883884-e945c9c0-c08f-455e-8791-094cab227bac.png)
In the experimental picture recall@1 Does it mean that K takes 1, that is, take the first function in the sorted function to judge whether it is similar
In the middle picture (fn), does n represent Poolsize=n?

**Comment by Hustcw** [comment]
Yes, that's right

**Comment by zzjss12** [comment]
Thank you.
How did you choose 32 functions and 10000 functions? Random selection?

**Comment by Hustcw** [comment]
Yes, we select the functions randomly.
