### ISSUE TITLE
run.py

### ISSUE THREAD

**Issue by zzjss12** [vul337/jTrans#6]
Hello,This appears when I run (run.py), and it prompts Strip file not found.
strip: ./dataset_strip/libcap-git-setcap-O0-00ac9f3e2f406891116850f0ddffd008.strip: No such file or directory

**Comment by zzjss12** [comment]
Whether it supports running on Windows system？

**Comment by Hustcw** [comment]
Hi, If you are running this script on Windows, the reason for this error is probably a missing `strip` command. You can try WSL or use `llvm-strip` instead.
