### ISSUE TITLE
Dataset filtering

### ISSUE THREAD

**Issue by zzjss12** [vul337/jTrans#7]
Hello, when building a data set with supervised training, I found that some functions have very different instructions under different compilation optimization levels.
For example, the instruction of a function is endbr64 Retn. Under another optimization level, it is endbr64 push~rbp mov~rbp, rsp sub~rsp, const mov~[rbp const], rdi lea~rdx, tag mov~rax, [rbp const] mov~[rax], rdx mov~rax, [rbp const] mov~rdi, rax call~foo nop leave retn
In fact, their semantics are very different. How do you deal with this situation?

**Comment by Hustcw** [comment]
These are some negative samples in the supervised dataset and account for only a small percentage of the dataset. You can filter the functions which are too short to clean the datasets.
