### ISSUE TITLE
Souce code of Baseline models

### ISSUE THREAD

**Issue by yanyou426** [vul337/jTrans#9]
Hello! Do you have plans to push source code of the baseline models (especially the 'Order matters')? Thanks a lot.

**Comment by wanshangfeng** [comment]
Hi！Could you share the source code of the baseline models ("Order matters")? It will be very helpful for us! Thanks.

**Comment by Hustcw** [comment]
We're doing a new research project :) 
You can try our new models at (https://github.com/Hustcw/CLAP) (https://github.com/Hustcw/CEBin)
